---
- hosts: all
  become: true
  tasks:
    - name: update yum packages
      yum:
        name: '*'
        state: latest
      register: yum_output

    - name: check for updated packages
      debug:
        var: yum_output

    - name: update cache
      command: dnf makecache
      become: true
